### ISSUE TITLE
Return delta info

### ISSUE THREAD

**Issue by fallemand** [flaviusone/coverage-diff#36]
Is it possible to also return the `totals` & `files` for the diff function? I would like to create my own table, but I can't find the deltas in the response.

```typescript
export function diff() {
...
const { regression, files, totals, diff, belowThreshold } = diffChecker(...);
...
return {
    diff,
    totals,
    files,
    results,
    regression,
    belowThreshold
  };
}
```

**Comment by fallemand** [comment]
I can create a PR if needed 👍

**Comment by flaviusone** [comment]
Hey @fallemand , I'm not sure it will be a good idea to expose these internals public api of the function. We should try keep the return object as slim as possible.

What I'm thinking we can do is to provide a custom formatter through the options field and if available just call it instead of the default one:
https://github.com/flaviusone/coverage-diff/blob/2ef6a47661656bdb7c6a8f821040c8142881aafa/src/index.ts#L36

**Comment by fallemand** [comment]
That will definitely will be nice to have, and I can even help with a PR.  
But still, I think it will be nice to expose the deltas in the form of an object. 
If I do the following: 
```
import diffChecker from "coverage-diff";
const { diff } = diffChecker(obj1, obj2)
```
I would expect to be able to see the difference between the two objects, and right now I can only print a table, or get the info only for the current coverage, but I can't get the deltas
If I get the object, I can perform whatever action I decide to do.
Wdyt?
